In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.ticker as mtick
import seaborn as sns

import wf_psf.script_utils as wf_script_utils

In [3]:
def define_plot_style():
    # Define plot paramters
    # Use seaborn style
    sns.set()
    
    plot_style = {
        'figure.figsize': (12,8),
        'figure.dpi': 200,
        'figure.autolayout':True,
        'lines.linewidth': 2,
        'lines.linestyle': '-',
        'lines.marker': 'o',
        'lines.markersize': 10,
        'legend.fontsize': 20,
        'legend.loc': 'best',
        'axes.titlesize': 24,
        'font.size': 22
    }
    mpl.rcParams.update(plot_style)

# Metrics

In [4]:
metrics_file = '../wf-outputs/metrics/metrics-poly_%s_cycles_256_%s_d%s_%sz_%s.npy'
dataset_list = [('2', 'no_proj', '2', '45'),('2', 'no_proj', '2', '60'),('5', 'no_proj', '2', '45'),('5', 'proj', '2', '45'),('5', 'proj', '2', '60'),('5', 'proj', '5', '45'),('9', 'no_proj', '2', '45'),('9', 'proj', '2', '45')]

n_cycles_list = [2,5,9]

In [5]:
n_realisations = 5
metrics_dict_list = []
for idx in range(n_realisations):
    metrics_dict_list_ = wf_script_utils.extract_shape_pix_results([np.load(metrics_file % (dataset+(str(idx),)), allow_pickle=True)[()] for dataset in dataset_list ])
    metrics_dict_list.append(metrics_dict_list_)

metrics_dict_list_np = np.array(metrics_dict_list)

In [8]:
metrics_mean = np.mean(metrics_dict_list_np,axis=0)
metrics_median = np.median(metrics_dict_list_np,axis=0)
metrics_std = np.std(metrics_dict_list_np, axis=0)
metrics_best = np.min(metrics_dict_list_np[:,2,:], axis=0)


In [39]:
print(metrics_dict_list_np[:,2,0])
print(metrics_dict_list_np[:,2,3])
print(metrics_dict_list_np[:,2,4])

[1.88103262 2.81541776 1.87898725 4.03888412 1.93350483]
[2.84832492 3.32769454 1.98153164 2.00902279 2.99401265]
[3.99563275 3.35177407 1.95338465 2.02785488 2.21465081]


In [10]:
print('n cycles | project | d_max param | n_zernikes   mean SR RMSE\n')
for idx, dataset in enumerate(dataset_list):
    print('%s cycles - %7s - d_max=%s - %sz' % dataset, ' ---> ', metrics_mean[2][idx], ' +/- ', metrics_std[2][idx],' | ' ,metrics_best[idx])

n cycles | project | d_max param | n_zernikes   mean SR RMSE

2 cycles - no_proj - d_max=2 - 45z  --->  2.5095653161406517  +/-  0.843432207349185  |  1.8789872527122498
2 cycles - no_proj - d_max=2 - 60z  --->  2.673838548362255  +/-  0.9607127966411424  |  1.9220437854528427
5 cycles - no_proj - d_max=2 - 45z  --->  3.655898980796337  +/-  0.9367677950643569  |  2.418283000588417
5 cycles -    proj - d_max=2 - 45z  --->  2.632117308676243  +/-  0.5427799055604208  |  1.9815316423773766
5 cycles -    proj - d_max=2 - 60z  --->  2.7086594328284264  +/-  0.818275761321406  |  1.9533846527338028
5 cycles -    proj - d_max=5 - 45z  --->  4.2982543259859085  +/-  0.3727477067059895  |  3.742995858192444
9 cycles - no_proj - d_max=2 - 45z  --->  4.28766630589962  +/-  0.5112127721789963  |  3.3537711948156357
9 cycles -    proj - d_max=2 - 45z  --->  4.0511442720890045  +/-  0.8070779865104847  |  2.5172319263219833


In [41]:
print('n cycles | project | d_max param | n_zernikes   median SR RMSE\n')
for idx, dataset in enumerate(dataset_list):
    print('%s cycles - %7s - d_max=%s - %sz' % dataset, ' ---> ', metrics_median[2][idx], ' +/- ', metrics_std[2][idx])

n cycles | project | d_max param | n_zernikes   median SR RMSE

2 cycles - no_proj - d_max=2 - 45z  --->  1.9335048273205757  +/-  0.843432207349185
2 cycles - no_proj - d_max=2 - 60z  --->  2.0488252863287926  +/-  0.9607127966411424
5 cycles - no_proj - d_max=2 - 45z  --->  3.9321020245552063  +/-  0.9367677950643569
5 cycles -    proj - d_max=2 - 45z  --->  2.8483249247074127  +/-  0.5427799055604208
5 cycles -    proj - d_max=2 - 60z  --->  2.214650809764862  +/-  0.818275761321406
5 cycles -    proj - d_max=5 - 45z  --->  4.448523372411728  +/-  0.3727477067059895
9 cycles - no_proj - d_max=2 - 45z  --->  4.420590028166771  +/-  0.5112127721789963
9 cycles -    proj - d_max=2 - 45z  --->  4.197609052062035  +/-  0.8070779865104847


# Evaluate only the parametric model

In [42]:
metrics_file = '../wf-outputs/metrics/metrics-poly_%s_cycles_256_eval_param_%s_d%s_%sz_%s.npy'
dataset_list = [('2', 'no_proj', '2', '45'),('2', 'no_proj', '2', '60'),('5', 'no_proj', '2', '45'),('5', 'proj', '2', '45'),('5', 'proj', '2', '60'),('5', 'proj', '5', '45'),('9', 'no_proj', '2', '45'),('9', 'proj', '2', '45')]

n_cycles_list = [2,5,9]

In [43]:
n_realisations = 5
metrics_dict_list = []
for idx in range(n_realisations):
    metrics_dict_list_ = wf_script_utils.extract_shape_pix_results([np.load(metrics_file % (dataset+(str(idx),)), allow_pickle=True)[()] for dataset in dataset_list ])
    metrics_dict_list.append(metrics_dict_list_)

metrics_dict_list_np = np.array(metrics_dict_list)

In [44]:
metrics_param_mean = np.mean(metrics_dict_list_np,axis=0)
metrics_param_median = np.median(metrics_dict_list_np,axis=0)
metrics_param_std = np.std(metrics_dict_list_np, axis=0)



In [45]:
print('n cycles | project | d_max param | n_zernikes   mean Param SR RMSE\n')
for idx, dataset in enumerate(dataset_list):
    print('%s cycles - %7s - d_max=%s - %sz' % dataset, ' ---> ', metrics_param_mean[2][idx], ' +/- ', metrics_std[2][idx])

n cycles | project | d_max param | n_zernikes   mean Param SR RMSE

2 cycles - no_proj - d_max=2 - 45z  --->  10.839911997318268  +/-  0.843432207349185
2 cycles - no_proj - d_max=2 - 60z  --->  11.287786960601807  +/-  0.9607127966411424
5 cycles - no_proj - d_max=2 - 45z  --->  12.353712320327759  +/-  0.9367677950643569
5 cycles -    proj - d_max=2 - 45z  --->  7.461188435554504  +/-  0.5427799055604208
5 cycles -    proj - d_max=2 - 60z  --->  6.62824422121048  +/-  0.818275761321406
5 cycles -    proj - d_max=5 - 45z  --->  13.290652185678482  +/-  0.3727477067059895
9 cycles - no_proj - d_max=2 - 45z  --->  14.938069581985474  +/-  0.5112127721789963
9 cycles -    proj - d_max=2 - 45z  --->  10.770474076271057  +/-  0.8070779865104847


### Projecting every model

In [46]:
metrics_file = '../wf-outputs/metrics/metrics-poly_%s_cycles_256_eval_param_%s_d%s_%sz_%s.npy'
dataset_list = [('2', 'no_proj_proj_end', '2', '45'),('2', 'no_proj_proj_end', '2', '60'),('5', 'no_proj_proj_end', '2', '45'),('5', 'proj', '2', '45'),('5', 'proj', '2', '60'),('5', 'proj', '5', '45'),('9', 'no_proj_proj_end', '2', '45'),('9', 'proj', '2', '45')]

n_cycles_list = [2,5,9]

In [47]:
n_realisations = 5
metrics_dict_list = []
for idx in range(n_realisations):
    metrics_dict_list_ = wf_script_utils.extract_shape_pix_results([np.load(metrics_file % (dataset+(str(idx),)), allow_pickle=True)[()] for dataset in dataset_list ])
    metrics_dict_list.append(metrics_dict_list_)

metrics_dict_list_np = np.array(metrics_dict_list)

In [48]:
metrics_param_proj_end_mean = np.mean(metrics_dict_list_np,axis=0)
metrics_param_proj_end_median = np.median(metrics_dict_list_np,axis=0)
metrics_param_proj_end_std = np.std(metrics_dict_list_np, axis=0)

In [49]:
print('n cycles | project | d_max param | n_zernikes   mean Param SR RMSE\n')
for idx, dataset in enumerate(dataset_list):
    print('%s cycles - %16s - d_max=%s - %sz' % dataset, ' ---> ', metrics_param_proj_end_mean[2][idx], ' +/- ', metrics_std[2][idx])

n cycles | project | d_max param | n_zernikes   mean Param SR RMSE

2 cycles - no_proj_proj_end - d_max=2 - 45z  --->  5.806027725338936  +/-  0.843432207349185
2 cycles - no_proj_proj_end - d_max=2 - 60z  --->  6.356428191065788  +/-  0.9607127966411424
5 cycles - no_proj_proj_end - d_max=2 - 45z  --->  9.14859876036644  +/-  0.9367677950643569
5 cycles -             proj - d_max=2 - 45z  --->  7.461188435554504  +/-  0.5427799055604208
5 cycles -             proj - d_max=2 - 60z  --->  6.62824422121048  +/-  0.818275761321406
5 cycles -             proj - d_max=5 - 45z  --->  13.290652185678482  +/-  0.3727477067059895
9 cycles - no_proj_proj_end - d_max=2 - 45z  --->  10.707536190748215  +/-  0.5112127721789963
9 cycles -             proj - d_max=2 - 45z  --->  10.770474076271057  +/-  0.8070779865104847


# WFE errors

In [50]:
metrics_file = '../wf-outputs/metrics/metrics-poly_%s_cycles_256_eval_param_%s_d%s_%sz_%s.npy'
dataset_list = [('2', 'no_proj_proj_end', '2', '45'),('2', 'no_proj_proj_end', '2', '60'),('5', 'no_proj_proj_end', '2', '45'),('5', 'proj', '2', '45'),('5', 'proj', '2', '60'),('5', 'proj', '5', '45'),('9', 'no_proj_proj_end', '2', '45'),('9', 'proj', '2', '45')]

n_cycles_list = [2,5,9]

In [51]:
n_realisations = 5
metrics_dict_list = []
for idx in range(n_realisations):
    metrics_dict_list_ = wf_script_utils.extract_opd_results([np.load(metrics_file % (dataset+(str(idx),)), allow_pickle=True)[()] for dataset in dataset_list ])
    metrics_dict_list.append(metrics_dict_list_)

metrics_dict_list_np = np.array(metrics_dict_list)

In [52]:
metrics_dict_list_np[0,2,0]

21.05453813772265

In [27]:
metrics_param_proj_end_mean = np.mean(metrics_dict_list_np,axis=0)
metrics_param_proj_end_median = np.median(metrics_dict_list_np,axis=0)
metrics_param_proj_end_std = np.std(metrics_dict_list_np, axis=0)

In [31]:
print('n cycles | project | d_max param | n_zernikes   mean Param OPD RMSE\n')
for idx, dataset in enumerate(dataset_list):
    print('%s cycles - %16s - d_max=%s - %sz' % dataset, ' ---> ', metrics_param_proj_end_mean[2][idx], ' +/- ', metrics_param_proj_end_std[2][idx])

n cycles | project | d_max param | n_zernikes   mean Param OPD RMSE

2 cycles - no_proj_proj_end - d_max=2 - 45z  --->  59.538323161681  +/-  45.781605650066915
2 cycles - no_proj_proj_end - d_max=2 - 60z  --->  81.92068838788694  +/-  37.921716154249815
5 cycles - no_proj_proj_end - d_max=2 - 45z  --->  91.79701670759388  +/-  29.464330208790443
5 cycles -             proj - d_max=2 - 45z  --->  74.26032859011416  +/-  39.335111831009336
5 cycles -             proj - d_max=2 - 60z  --->  95.31287064351417  +/-  44.13749166054337
5 cycles -             proj - d_max=5 - 45z  --->  121.45078449504688  +/-  7.355585737704699
9 cycles - no_proj_proj_end - d_max=2 - 45z  --->  102.14559778231435  +/-  22.279322499130664
9 cycles -             proj - d_max=2 - 45z  --->  112.63092088842977  +/-  29.681921160214884
